### ISSUE TITLE
Properly translate fetch/vertex shaders.

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#221]
A fetch shader at its core is simply a callable subroutine of the vertex shader.  A proper implementation of fetch shaders means that we should be handling as part of the vertex shader translation step (ie: pass fetch shader to vertex shaders if its set, and when they trigger CALL_FS, we translate the fetch shader's instruction up to its RETURN call).  This is particularly necessary as some games have a fetch shader specified but then never call it, instead opting for inline VTX_FETCH instructions within the vertex shader.  This is further complicated as the vertex fetch instruction seems to allow arbitrary fetching of data from the attribute buffers through their SRC attribute.  This means that potentially the fetch is not per-vertex as is the case with GLSL, this is particularly troublesome for shaders which do VTX_FETCH's later in the shader after registers have been modified and we will need to work out what they are actually targeting.

**Comment by brett19** [comment]
I've partially worked on solving this, but I need a good example of a vertex shader which calls VTX_FETCH without using the fetch shader.

**Comment by brett19** [comment]
As a side-note, we currently assume XYZW registers have specific meaning within the context of a VTX_FETCH, but I believe this may be incorrect and instead the step rates actually are stored into R0.[x,y,z,w], but this might not be true for VTX_FETCH instructions later in the program.

**Comment by achurch** [comment]
I don't know if it's a "good" example, but here's one from Xenoblade:
```
GX2VertexShader:
  size: 1744
  mode: UniformBlock
  uniformBlockCount: 2
    Block 0
      name: U_Bone
      offset: 1
      size: 96
    Block 1
      name: U_Mdl
      offset: 2
      size: 160
  uniformVarCount: 6
    Var 0
      name: gmSkinMtx
      type: 26
      count: 2
      offset: 0
      block: 0
    Var 1
      name: gmSkinMtx[0]
      type: 26
      count: 2
      offset: 0
      block: 0
    Var 2
      name: gmSkinMtx[1]
      type: 26
      count: 2
      offset: 12
      block: 0
    Var 3
      name: gmWVP
      type: Matrix4x4
      count: 1
      offset: 0
      block: 1
    Var 4
      name: gmWorld
      type: 26
      count: 1
      offset: 16
      block: 1
    Var 5
      name: gmWorldView
      type: 26
      count: 1
      offset: 28
      block: 1
  intialValueCount: 0
  loopVarCount: 0
  samplerVarCount: 0
  attribVarCount: 2
    Var 0
      name: vInx
      type: Int4
      count: 0
      location: 1
    Var 1
      name: vWet
      type: Float3
      count: 0
      location: 0

Disassembly:
00 CALL_FS NO_BARRIER

01 ALU ADDR(32) CNT(25) KCACHE0(cb2, 0 to 15)
    0 x: DOT4            ____, R2.x, 1.0f
      y: DOT4            ____, R2.y, 1.0f
      z: DOT4            ____, R2.z, 1.0f
      w: DOT4            ____, (0x80000000, -0), 0.0f
      t: MULLO_INT       R3.y, R1.x, (0x00000003, 4.2039e-45) SCL_210

    1 x: ADD_INT         R0.x, PS0, (0x00000002, 2.8026e-45)
      y: ADD             R15.y, -PV0.x, 1.0f CLAMP
      z: MUL             R15.z, KCACHE0[7].w, 1.0f
      w: ADD_INT         R2.w, PS0, 1
      t: MULLO_INT       R0.z, R1.y, (0x00000003, 4.2039e-45) SCL_210

    2 x: MUL             R15.x, KCACHE0[8].w, 1.0f
      y: ADD_INT         R0.y, PS1, 1
      z: MUL             R16.z, KCACHE0[9].w, 1.0f
      w: ADD_INT         R0.w, PS1, (0x00000002, 2.8026e-45)
      t: MULLO_INT       R3.x, R1.z, (0x00000003, 4.2039e-45) SCL_210

    3 x: MOV             R1.x, 0.0f
      y: ADD_INT         R1.y, PS2, (0x00000002, 2.8026e-45)
      z: ADD_INT         R1.z, PS2, 1
      w: MOV             R1.w, (0x3F800000, 1)
      t: MULLO_INT       R3.z, R1.w, (0x00000003, 4.2039e-45) SCL_210

02 TEX ADDR(192) CNT(8)

    4    FETCH           R4.xyzw, R0.x, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

    5    FETCH           R5.xyzw, R0.w, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

    6    FETCH           R6.xyzw, R2.w, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

    7    FETCH           R7.xyzw, R0.y, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

    8    FETCH           R8.xyzw, R1.y, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

    9    FETCH           R9.xyzw, R3.y, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

   10    FETCH           R10.xyzw, R0.z, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

   11    FETCH           R11.xyzw, R1.z, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

03 ALU ADDR(57) CNT(11)
   12 x: MUL             R0.x, R2.x, R4.y
      y: ADD_INT         R3.y, R3.z, 1
      z: MUL             R1.z, R2.x, R4.x
      w: ADD_INT         R2.w, R3.z, (0x00000002, 2.8026e-45)
      t: MUL             R0.w, R2.x, R4.z

   13 x: MUL             R4.x, R2.x, R4.w VEC_021
      y: MUL             R4.y, R2.y, R5.x
      z: MUL             R4.z, R2.y, R5.y
      w: MUL             R4.w, R2.y, R5.z
      t: MUL             R5.w, R2.y, R5.w

04 TEX ADDR(208) CNT(4)

   14    FETCH           R12.xyzw, R2.w, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

   15    FETCH           R13.xyzw, R3.x, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

   16    FETCH           R14.xyzw, R3.y, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

   17    FETCH           R3.xyzw, R3.z, b129 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(0)

05 EXP_DONE POS0, R1.xxxw

06 ALU ADDR(68) CNT(112) KCACHE0(cb2, 0 to 15)
   18 x: ADD             R125.x, R1.z, R4.y VEC_021
      y: ADD             R126.y, R0.w, R4.w
      z: ADD             R125.z, R0.x, R4.z
      w: ADD             R125.w, R4.x, R5.w VEC_120
      t: MUL             R126.z, R2.x, R6.y

   19 x: MUL             R127.x, R2.x, R6.x
      y: MUL             R127.y, R2.x, R6.z
      z: MUL             R127.z, R2.y, R7.x VEC_021
      w: MUL             R127.w, R2.x, R6.w
      t: MUL             R126.x, R2.y, R7.y

   20 x: MUL             R124.x, R2.z, R8.y VEC_201
      y: MUL             ____, R2.y, R7.w VEC_120
      z: MUL             ____, R2.y, R7.z VEC_102
      w: MUL             R126.w, R2.z, R8.x VEC_201
      t: MUL             R124.z, R2.z, R8.z

   21 x: ADD             R126.x, R127.x, R127.z
      y: MUL             ____, R2.z, R8.w
      z: ADD             R127.z, R126.z, R126.x VEC_210
      w: ADD             R124.w, R127.y, PV20.z
      t: ADD             R8.w, R127.w, PV20.y

   22 x: ADD             R8.x, R125.z, R124.x
      y: ADD             R124.y, R125.w, PV21.y
      z: ADD             R8.z, R126.y, R124.z
      w: ADD             R7.w, R125.x, R126.w
      t: MUL             R124.x, R2.x, R9.y

   23 x: MUL             R125.x, R2.y, R10.x
      y: MUL             R126.y, R2.x, R9.w
      z: MUL             R125.z, R2.x, R9.z
      w: MUL             R126.w, R2.x, R9.x VEC_021
      t: MUL             R125.w, R2.y, R10.y

   24 x: MUL             R127.x, R2.y, R10.z VEC_102
      y: MUL             R127.y, R2.z, R11.x VEC_201
      z: MUL             R124.z, R2.y, R10.w VEC_120
      w: MUL             R127.w, R2.z, R11.y VEC_201
      t: MUL             R10.x, R2.z, R11.z

   25 x: MUL             R11.x, R15.y, R12.x
      y: MUL             R125.y, R15.y, R12.y
      z: MUL             R126.z, R2.z, R11.w VEC_021
      w: MUL             R11.w, R15.y, R12.z
      t: MUL             R12.w, R15.y, R12.w

   26 x: ADD             R127.x, R126.w, R125.x
      y: ADD             R126.y, R125.z, R127.x VEC_021
      z: ADD             R127.z, R124.x, R125.w VEC_021
      w: ADD             R127.w, R126.y, R124.z
      t: ADD             R125.x, R127.z, R127.w

   27 x: ADD             R124.x, R7.w, R11.x
      y: ADD             R11.y, R8.w, R126.z VEC_102
      z: ADD             R126.z, R124.w, R10.x VEC_201
      w: ADD             R126.w, R126.x, R127.y VEC_201
      t: MUL             R127.y, R2.z, R13.y

   28 x: MUL             R126.x, R2.z, R13.x VEC_201
      y: ADD             R12.y, R8.z, R11.w
      z: ADD             R124.z, R8.x, R125.y VEC_120
      w: ADD             R125.w, R124.y, R12.w VEC_021
      t: MUL             R124.w, R2.z, R13.z

   29 x: MUL             ____, R2.z, R13.w VEC_021
      y: MUL             R125.y, R15.y, R14.y
      z: MUL             R125.z, R15.y, R14.z
      w: MUL             ____, R15.y, R14.x
      t: MUL             R124.y, R15.y, R14.w

   30 x: ADD             R127.x, R127.z, R127.y
      y: ADD             R127.y, R127.w, PV29.x
      z: ADD             R127.z, R126.y, R124.w
      w: ADD             R127.w, R127.x, R126.x
      t: ADD             R13.x, R126.w, PV29.w

   31 x: MUL             R2.x, R124.x, KCACHE0[7].z
      y: ADD             R11.y, R126.z, R125.z
      z: ADD             R2.z, R125.x, R125.y VEC_120
      w: ADD             R13.w, R11.y, R124.y
      t: MUL             R126.x, R124.z, KCACHE0[7].z

   32 x: MUL             R125.x, R15.y, R3.z
      y: MUL             R125.y, R15.y, R3.x
      z: MUL             R126.z, R15.y, R3.w
      w: MUL             R126.w, R15.y, R3.y
      t: MUL             R124.w, R12.y, KCACHE0[7].z

   33 x: MUL             R15.x, R124.x, KCACHE0[8].z
      y: MUL             R124.y, R12.y, KCACHE0[8].z
      z: MULADD          R125.z, KCACHE0[7].z, R125.w, R15.z
      w: MUL             R3.w, R124.z, KCACHE0[8].z
      t: MULADD          R126.y, KCACHE0[8].z, R125.w, R15.x VEC_021

   34 x: MULADD          R124.x, KCACHE0[9].z, R125.w, R16.z
      y: MUL             R125.y, R12.y, KCACHE0[9].z
      z: MUL             R124.z, R124.z, KCACHE0[9].z
      w: MUL             R127.w, R124.x, KCACHE0[9].z
      t: ADD             R3.x, R127.w, R125.y

   35 x: MULADD          R127.x, KCACHE0[7].y, R2.z, R126.x
      y: ADD             R127.y, R127.z, R125.x
      z: ADD             R126.z, R127.x, R126.w
      w: ADD             R125.w, R127.y, R126.z VEC_021
      t: MULADD          R126.w, KCACHE0[7].y, R11.y, R124.w VEC_021

   36 x: MULADD          R126.x, KCACHE0[8].y, R13.x, R15.x
      y: MULADD          R124.y, KCACHE0[7].y, R13.x, R2.x VEC_210
      z: MULADD          R125.z, KCACHE0[7].y, R13.w, R125.z
      w: MULADD          R124.w, KCACHE0[8].y, R2.z, R3.w
      t: MULADD          R127.z, KCACHE0[8].y, R11.y, R124.y VEC_120

   37 x: MULADD          R124.x, KCACHE0[9].y, R11.y, R125.y
      y: MULADD          R126.y, KCACHE0[8].y, R13.w, R126.y VEC_120
      z: MULADD          R124.z, KCACHE0[9].y, R2.z, R124.z
      w: MULADD          R127.w, KCACHE0[9].y, R13.x, R127.w VEC_201
      t: MULADD          R125.x, KCACHE0[9].y, R13.w, R124.x VEC_021

   38 x: MULADD          R2.x, KCACHE0[7].x, R3.x, R124.y
      y: MULADD          R2.y, KCACHE0[7].x, R126.z, R127.x VEC_120
      z: MULADD          R2.z, KCACHE0[7].x, R127.y, R126.w
      w: MULADD          R2.w, KCACHE0[7].x, R125.w, R125.z VEC_201
      t: MULADD          R11.x, KCACHE0[8].x, R3.x, R126.x VEC_120

   39 x: MULADD          R3.x, KCACHE0[9].x, R3.x, R127.w
      y: MULADD          R11.y, KCACHE0[8].x, R126.z, R124.w VEC_210
      z: MULADD          R11.z, KCACHE0[8].x, R127.y, R127.z VEC_120
      w: MULADD          R11.w, KCACHE0[8].x, R125.w, R126.y VEC_210
      t: MULADD          R3.y, KCACHE0[9].x, R126.z, R124.z VEC_120

   40 z: MULADD          R3.z, KCACHE0[9].x, R127.y, R124.x
      w: MULADD          R3.w, KCACHE0[9].x, R125.w, R125.x VEC_021

07 EXP PARAM0, R2.xyzw

08 MEM_STREAM0 MEM_UNKNOWN_FORMAT

09 EXP PARAM1, R11.xyzw NO_BARRIER

10 MEM_STREAM0 MEM_UNKNOWN_FORMAT

11 EXP_DONE PARAM2, R3.xyzw NO_BARRIER

12 MEM_STREAM0 MEM_UNKNOWN_FORMAT

13 ALU ADDR(180) CNT(1)
   41 x: NOP             ____

14 NOP
```
