### ISSUE TITLE
Better config file.

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#414]
1. Deduplicate between decaf-cli and decaf-sdl.
2. Move away from the cereal json parser, it's too strict in it's requirements.

Maybe TOML or YAML?

**Comment by achurch** [comment]
I'm leaning toward XML -- it may be verbose, but it's well standardized and there are solid supporting libraries. Plus I assume the desired end state is a config UI, so the use case of directly editing the config should be less important in the long run, I think?

**Comment by brett19** [comment]
YAML, JSON, INI are all well standardized, but have the additional property of being easily editable by hand.  Why not?

**Comment by achurch** [comment]
INI I'll grant is easily editable, but it's poor at handling structured data -- one level you can do fine, but when you start nesting stuff it gets hard to keep track of the structure. There's already a fair amount of nesting in the config, or I probably would have suggested this.

YAML and JSON "easily editable by hand"? Clearly you have a different definition than I do...

**Comment by ds84182** [comment]
YAML is way easier to edit by hand than JSON. I'd group YAML with INI.

**Comment by exjam** [comment]
This is what our config.json could look like in TOML:
```

**Comment by ds84182** [comment]
[almost] equivalent YAML:

```yaml
debugger:
  enabled: true
  break-on-entry: true
  gdb-stub:
    enabled: true
    port: 2159

gpu:
  debug: false
  debug-filters:
    - filter-a
    - filter-b
  force-sync: false

gx2:
  dump-textures: false
  dump-shaders: false

input-devices:
  - type: keyboard
    buttons:
      up: 82
      down: 81
      left: 80
      right: 79
      a: 27
      b: 29
      x: 22
      y: 4
      trigger-r: 8
      trigger-l: 26
      trigger-zr: 21
      trigger-zl: 20
      stick-l: 98
      stick-r: 88
      plus: 30
      minus: 31
      home: 32
      sync: 33
    left-stick:
      up: 96
      down: 90
      left: 92
      right: 94
    right-stick:
      up: -1
      down: -1
      left: -1
      right: -1
  - type: joystick
    buttons:
      up: -2
      down: -2
      left: -2
      right: -2
      a: -2
      b: -2
      x: -2
      y: -2
      trigger-r: -2
      trigger-l: -2
      trigger-zr: -2
      trigger-zl: -2
      stick-l: -2
      stick-r: -2
      plus: -2
      minus: -2
      home: -2
      sync: -2
    left-stick:
      x: -2
      invert-x: false
      y: -2
      invert-y: false
    right-stick:
      x: -2
      invert-x: false
      y: -2
      invert-y: false

jit:
  enabled: true
  verify: false
  code-cache-size: 1024mb
  data-cache-size: 256mb
  rodata-read-only: true
  opt-flags:
    - BASIC
    - DECONDITION
    - DSE
    - FOLD_CONSTANTS
    - PPC_PAIRED_LWARX_STWCX
    - X86_BRANCH_ALIGNMENT
    - X86_CONDITION_CODES
    - X86_FIXED_REGS
    - X86_FORWARD_CONDITIONS
    - X86_STORE_IMMEDIATE

log:
  level: debug
  async: false
  to-file: true
  to-stdout: false
  kernel-trace: true
  kernel-trace-res: false
  kernel-trace-filters: [ "+*" ]
  branch-trace: false

sound:
  dump-sounds: false
  frame-length: 30

system:
  region: 2
  mlc-path: mlc
  sdcard-path: sdcard
  lle-modules:
    - erreula.rpl

ui:
  background-color: [ 153, 51, 51 ]
```
